# Generated by Django 4.0.4 on 2022-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lme',
            field=models.BooleanField(default=False),
        ),
    ]
