# Generated by Django 4.0.4 on 2022-05-15 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingAndMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lme_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('topic_covered', models.CharField(max_length=100)),
                ('remarks_by_mentor', models.TextField()),
                ('action_points', models.TextField()),
                ('next_meeting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('no_of_female_employees', models.IntegerField()),
                ('no_of_male_employees', models.IntegerField()),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('year_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='LMESales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('lme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.lme')),
                ('stove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.stove')),
            ],
        ),
        migrations.AddField(
            model_name='lme',
            name='types_of_stove',
            field=models.ManyToManyField(to='environment.stove'),
        ),
    ]
