# Generated by Django 4.0.4 on 2022-05-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Factory', 'verbose_name_plural': 'Factories'},
        ),
        migrations.AlterField(
            model_name='lme',
            name='phone_number',
            field=models.CharField(help_text='07xx xxx xxx', max_length=20),
        ),
        migrations.AlterField(
            model_name='stove',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.retailer'),
        ),
    ]
