# Generated by Django 4.0.4 on 2022-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lme',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
