# Generated by Django 4.0.4 on 2022-05-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_alter_factory_options_alter_lme_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingandmentorship',
            name='lme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.lme'),
        ),
    ]
