# Generated by Django 4.0.4 on 2022-05-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_coachingandmentorship_lme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingandmentorship',
            name='lme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='environment.lme'),
            preserve_default=False,
        ),
    ]
