# Generated by Django 4.0.4 on 2022-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_remove_lme_year_of_birth_lme_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lme',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True),
        ),
    ]
