# Generated by Django 4.0.4 on 2022-05-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_alter_coachingandmentorship_lme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingandmentorship',
            name='lme_name',
        ),
    ]
