# Generated by Django 4.0.4 on 2022-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_remove_coachingandmentorship_lme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmesales',
            name='stove_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
