# Generated by Django 4.0.4 on 2022-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_lmesales_stove_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lmesales',
            options={'verbose_name': 'LME Sales', 'verbose_name_plural': 'LME Sales'},
        ),
        migrations.AlterField(
            model_name='lme',
            name='no_of_female_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lme',
            name='no_of_male_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lme',
            name='year_of_birth',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
