# Generated by Django 4.0.4 on 2022-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0007_alter_lmesales_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stove',
            name='retailer',
        ),
        migrations.AddField(
            model_name='lme',
            name='retailer_or_installer',
            field=models.CharField(choices=[('RET', 'RETAILER'), ('INS', 'INSTALLER')], default='INS', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lmesales',
            name='date_of_purchase',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.DeleteModel(
            name='Retailer',
        ),
    ]
