# Generated by Django 4.0.4 on 2022-09-26 11:29

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment', '0008_treegrowing_planting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treegrowing',
            name='planting_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='click on the top right to search', null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='LessonLearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_summary', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lessons Learnt',
            },
        ),
    ]
