# Generated by Django 4.0.4 on 2022-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0009_monthlylmesales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stove',
            name='name',
            field=models.CharField(choices=[('KCJ', 'KCJ'), ('JKI', 'Jiko Kisasa'), ('MLP', 'Multipurpose'), ('LNR', 'Liners'), ('RCK', 'Rocket')], max_length=50),
        ),
    ]
