# Generated by Django 4.0.4 on 2022-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0010_alter_stove_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmesales',
            name='date_of_purchase',
            field=models.DateField(help_text='DD-MM-YYYY'),
        ),
        migrations.AlterField(
            model_name='stove',
            name='name',
            field=models.CharField(choices=[('KCJ', 'KCJ'), ('JIKO_KISASA', 'Jiko Kisasa'), ('MULTIPURPOSE', 'Multipurpose'), ('LINERS', 'Liners'), ('ROCKET', 'Rocket')], max_length=50),
        ),
    ]
