# Generated by Django 4.0.4 on 2022-05-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0011_alter_lmesales_date_of_purchase_alter_stove_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingAndMentorshipActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=140)),
                ('venue', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_attendees', models.IntegerField(default=0)),
                ('number_of_female_attendees', models.IntegerField(default=0)),
                ('number_of_male_attendees', models.IntegerField(default=0)),
                ('number_below_20', models.IntegerField(default=0)),
                ('number_20_29', models.IntegerField(default=0)),
                ('number_30_39', models.IntegerField(default=0)),
                ('number_40_49', models.IntegerField(default=0)),
                ('number_50_59', models.IntegerField(default=0)),
                ('number_60_69', models.IntegerField(default=0)),
                ('number_70_79', models.IntegerField(default=0)),
                ('number_80_above', models.IntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.factory')),
                ('lme_attendees', models.ManyToManyField(related_name='activities', to='environment.lme')),
            ],
        ),
    ]
