# Generated by Django 4.0.4 on 2022-05-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0012_coachingandmentorshipactivities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachingAndMentorshipActivities',
            new_name='CoachingAndMentorshipActivity',
        ),
        migrations.AlterModelOptions(
            name='coachingandmentorshipactivity',
            options={'verbose_name': 'Coaching and Mentorship Activity', 'verbose_name_plural': 'Coaching and Mentorship Activities'},
        ),
    ]
