# Generated by Django 4.0.4 on 2022-05-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0014_alter_coachingandmentorshipactivity_lme_attendees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachingAndMentorshipActivity',
            new_name='Training',
        ),
    ]
