# Generated by Django 4.0.4 on 2022-05-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0015_rename_coachingandmentorshipactivity_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Training Activity', 'verbose_name_plural': 'Training Activities'},
        ),
        migrations.AlterField(
            model_name='stove',
            name='name',
            field=models.CharField(choices=[('KCJ', 'KCJ'), ('JIKO_KISASA', 'Jiko Kisasa'), ('MULTIPURPOSE', 'Multipurpose'), ('LINERS', 'Liners'), ('ROCKET', 'Rocket')], max_length=20),
        ),
        migrations.CreateModel(
            name='TreeGrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=120, null=True)),
                ('venue', models.CharField(blank=True, max_length=60, null=True)),
                ('trees_planted', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('indigenous_trees', models.IntegerField(default=0)),
                ('exotic_trees', models.IntegerField(default=0)),
                ('fruit_trees', models.IntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.factory')),
            ],
            options={
                'verbose_name': 'Tree Growing',
                'verbose_name_plural': 'Tree Growing',
            },
        ),
    ]
