# Generated by Django 4.0.4 on 2022-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0016_alter_training_options_alter_stove_name_treegrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
