# Generated by Django 4.0.4 on 2022-05-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0018_county_subcounty_factory_county_obj_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='county',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='county_obj',
        ),
        migrations.AddField(
            model_name='factory',
            name='county_located',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.county'),
        ),
    ]
