# Generated by Django 4.0.4 on 2022-05-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0019_remove_factory_county_remove_factory_county_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='county_located',
            new_name='county',
        ),
    ]
