# Generated by Django 4.0.4 on 2022-05-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0021_region_zone_remove_factory_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='region_located',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='factory',
            old_name='zone_located',
            new_name='zone',
        ),
    ]
