# Generated by Django 4.0.4 on 2022-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0022_rename_region_located_factory_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='factories/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factory CSV Upload',
                'verbose_name_plural': 'Factory CSV Uploads',
            },
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name_plural': 'Sub-Counties'},
        ),
    ]
