# Generated by Django 4.0.4 on 2022-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0023_factorycsvupload_alter_county_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lme',
            name='county',
        ),
        migrations.RemoveField(
            model_name='lme',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='lme',
            name='ward',
        ),
    ]
