# Generated by Django 4.0.4 on 2022-05-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0024_remove_lme_county_remove_lme_sub_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lme',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.county'),
        ),
        migrations.AddField(
            model_name='lme',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.subcounty'),
        ),
        migrations.AddField(
            model_name='lme',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.ward'),
        ),
    ]
