# Generated by Django 4.0.4 on 2022-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0025_lme_county_lme_sub_county_lme_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='factories/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_lme_file', models.BooleanField(default=False)),
                ('is_factory_file', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Factory CSV Upload',
                'verbose_name_plural': 'Factory CSV Uploads',
            },
        ),
        migrations.DeleteModel(
            name='FactoryCSVUpload',
        ),
        migrations.AlterField(
            model_name='lme',
            name='year_of_birth',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
