# Generated by Django 4.0.4 on 2022-05-21 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment', '0026_csvupload_delete_factorycsvupload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvupload',
            options={'verbose_name': ' CSV Upload', 'verbose_name_plural': ' CSV Uploads'},
        ),
        migrations.CreateModel(
            name='CustomSalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_lme', models.CharField(blank=True, max_length=60, null=True)),
                ('query_month', models.CharField(blank=True, max_length=15, null=True)),
                ('query_year', models.IntegerField(blank=True, null=True)),
                ('query_factory', models.CharField(blank=True, max_length=50, null=True)),
                ('query_jiko_kisasa', models.BooleanField(default=False)),
                ('query_kcj', models.BooleanField(default=False)),
                ('query_multipurpose', models.BooleanField(default=False)),
                ('query_liners', models.BooleanField(default=False)),
                ('query_rocket', models.BooleanField(default=False)),
                ('query_start_date', models.DateField(blank=True, null=True)),
                ('query_end_date', models.DateField(blank=True, null=True)),
                ('no_query_results', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Sales Report',
                'verbose_name_plural': 'Custom Sales Reports',
            },
        ),
    ]
